controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

article_create:
    path: /article/create
    controller: App\Controller\ArticleController::create
